# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aab8c9913eec71f8eb25b8ba9f26b76e1d4232162be4a9ba4a8b864106e2d4b1fd493027fa133c8784674c350e4307668bedf47e050ff28c3f0f5efc58708006

test:
  secret_key_base: 052a44ee578fa819f226b31d9f7f0d934c517abfd7e5a284611164ea0b32ac1a0b6779db560a397bbae038f38458d9f2b78b7e3d27cc4c17af55659ef6f124ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
